name: Terraform CI/CD

on:
  push:
    branches:
      - main
jobs:
  plan_and_apply:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: $ {{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY_ID: $ {{ secret.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repoisitory
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.5.0

      - name: Terraform Plan
        run: terraform plan
