name: Terraform Plan Check

on:
  push:
    branches:
      - main
jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repoisitory
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.5.0

      - name: Terraform Plan
        run: terraform plan
